name: Azure Static Web Apps CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened, closed]
        branches:
            - main

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    install-deps:
        if: github.repository == 'jerensl/www.jerensl.com'
        name: Install dependencies
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Setup Node.js 16.x
              uses: actions/setup-node@v4
              with:
                  node-version: '16.x'
            - name: Install locked dependencies
              run: yarn install --frozen-lockfile
            - name: Cache dependencies
              uses: actions/cache@v1
              id: cache-deps
              with:
                  path: '.'
                  key: ${{ github.sha }}
    build_and_deploy_job:
        if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
        runs-on: ubuntu-latest
        name: Build and Deploy Job
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true
            - name: Build And Deploy
              id: builddeploy
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
                  action: 'upload'
                  ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
                  # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
                  app_location: '/' # App source code path
                  api_location: '' # Api source code path - optional
                  output_location: 'out' # Built app content directory - optional
                  ###### End of Repository/Build Configurations ######
              env:
                  NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY }}
                  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
                  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
                  NEXT_PUBLIC_REST_API: ${{ secrets.NEXT_PUBLIC_REST_API }}
    build_docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Detect package manager
              id: detect-package-manager
              run: |
                  if [ -f "${{ github.workspace }}/yarn.lock" ]; then
                  echo "manager=yarn" >> $GITHUB_OUTPUT
                  echo "command=install" >> $GITHUB_OUTPUT
                  echo "runner=yarn" >> $GITHUB_OUTPUT
                  exit 0
                  elif [ -f "${{ github.workspace }}/package.json" ]; then
                  echo "manager=npm" >> $GITHUB_OUTPUT
                  echo "command=ci" >> $GITHUB_OUTPUT
                  echo "runner=npx --no-install" >> $GITHUB_OUTPUT
                  exit 0
                  else
                  echo "Unable to determine package manager"
                  exit 1
                  fi
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: '16'
                  cache: ${{ steps.detect-package-manager.outputs.manager }}
            - name: Deploy Storybook Docs
              uses: bitovi/github-actions-storybook-to-github-pages@v1.0.1
              with:
                  install_command: yarn install # default: npm ci
                  build_command: yarn build-storybook # default: npm run build-storybook
                  path: storybook-static # default: dist/storybook
                  checkout: false # default: true
    close_pull_request_job:
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        runs-on: ubuntu-latest
        name: Close Pull Request Job
        steps:
            - name: Close Pull Request
              id: closepullrequest
              uses: Azure/static-web-apps-deploy@v1
              with:
                  azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
                  action: 'close'
                  app_location: '/' # App source code path
                  api_location: '' # Api source code path - optional
                  output_location: 'out' # Built app content directory - optional
